import type { Metadata } from "next";
import ThemeRegistry from "./component/ThemeRegistry";

import "./globals.css";
export const metadata: Metadata = {
  title: " My LinkedIn",
  description: "Generated by linkedIn website",
  icons :{
    icon : '/favicon.ico'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  cz-shortcut-listen="true"
  >
    <ThemeRegistry>
        {children}
    </ThemeRegistry>
      </body>
    </html>
  );
}
