import type { Metadata } from "next";

import "./globals.css";
export const metadata: Metadata = {
  title: "LinkedIn:Log In or Sign Up",
  description: "Generated by linkedIn website",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
